### PR TITLE
Issue133

### PR DESCRIPTION
**Pull request by tomtinkerer**
Resolves deletion described in Issue #133

### CODE REVIEW

**Comment by tomtinkerer** [comment]
IGNORE THIS PULL REQUEST

It has been wrapped into another one

**Comment by rlfrahm** [comment]
0eb8d2b should not be included in this commit.

**Comment by tomtinkerer** [comment]
Ryan, I asked in #120 about standard syncing practices in GitHub; I synced my development branch to nrem/development. 0eb8d2b is that sync. How else does one sync without having to wipe the repository through the GitHub.com interface? I'm trying to solve the root of this problem, so no systemic problems cause so many pull request rejections in the future.

**Comment by rlfrahm** [comment]
@tomtinkerer, here is an excellent explanation of how you sync your fork: https://help.github.com/articles/syncing-a-fork/

**Comment by tomtinkerer** [comment]
Thanks for the explanation and assistance today!

**Comment by tomtinkerer** [comment]
resolved in other PR

**Pull request closed without merging**
