### PR TITLE
Issue146

### PR DESCRIPTION
**Pull request by tomtinkerer**
Resolves changes/additions described in Issue #146

### CODE REVIEW

**Comment by rlfrahm** [comment]
0eb8d2b should not be included in this commit.

**Comment by rlfrahm** [comment]
See the following link on how to update your fork: http://stackoverflow.com/a/7244456/2824391

**Comment by tomtinkerer** [comment]
Thanks

**Comment by tomtinkerer** [comment]
resolved in other PR

**Pull request closed without merging**
